Add R compiler configuration extraction to configure.ac

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2133,6 +2133,16 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+# From https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Configure-and-cleanup :
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+
 # Following lines kindly supplied by Dirk Eddelbuettel
 ## Use gsl-config to find arguments for compiler and linker flags
 ##
